name: gestion_contact
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Hive pour la base de données locale
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Permissions & Actions
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0

  # Image picker (pour photo)
  image_picker: ^1.0.4

  # UI
  flutter_slidable: ^3.0.1
  intl: ^0.18.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Générateur de code Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

# Section flutter (UNE SEULE FOIS)
flutter:
  uses-material-design: true
  
  assets:
    - assets/